openapi: 3.1.0
info:
  title: My API
  version: 1.0.0
paths:
  /users:
    post:
      summary: Create a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: The username of the new user
                  example: john_doe
                password:
                  type: string
                  description: The password of the new user
                  example: secret123
              required:
                - username
                - password
      responses:
        "201":
          description: User created successfully
        "400":
          description: Bad request
