CREATE TABLE "onboarding" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "image" varchar,
  "title" varchar NOT NULL,
  "description" text NOT NULL
);

CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar(50) UNIQUE NOT NULL,
  "hashed_password" varchar NOT NULL,
  "full_name" varchar NOT NULL,
  "email" varchar UNIQUE NOT NULL,
  "avatar" varchar,
  "role" varchar(20) NOT NULL DEFAULT 'standard',
  "birth_date" date NOT NULL DEFAULT '0001-01-01',
  "password_changed_at" timestamptz NOT NULL DEFAULT '0001-01-01 00:00:00Z',
  "created_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50) UNIQUE NOT NULL
);

CREATE TABLE "posts" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "title" varchar(255) NOT NULL,
  "content" text NOT NULL,
  "cover_image" varchar(255),
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now()),
  "likes" int NOT NULL DEFAULT 0
);

CREATE TABLE "tags" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50) UNIQUE NOT NULL
);

CREATE TABLE "post_tags" (
  "post_id" int NOT NULL,
  "tag_id" int NOT NULL,
  PRIMARY KEY ("post_id", "tag_id")
);

CREATE TABLE "post_categories" (
  "post_id" int NOT NULL,
  "category_id" int NOT NULL,
  PRIMARY KEY ("post_id", "category_id")
);

CREATE TABLE "featured_stories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "post_id" int NOT NULL,
  "featured_date" date DEFAULT (current_date)
);

CREATE TABLE "profiles" (
  "user_id" int PRIMARY KEY,
  "bio" text,
  "post_count" int DEFAULT 0,
  "like_count" int DEFAULT 0,
  "follower_count" int DEFAULT 0
);

CREATE TABLE "user_posts" (
  "user_id" int NOT NULL,
  "post_id" int NOT NULL,
  PRIMARY KEY ("user_id", "post_id")
);

CREATE TABLE "user_followers" (
  "user_id" int NOT NULL,
  "follower_id" int NOT NULL,
  PRIMARY KEY ("user_id", "follower_id")
);

CREATE TABLE "comments" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "post_id" int NOT NULL,
  "user_id" int NOT NULL,
  "content" text NOT NULL,
  "created_at" timestamptz DEFAULT (now())
);

CREATE TABLE "post_likes" (
  "post_id" int NOT NULL,
  "user_id" int NOT NULL,
  PRIMARY KEY ("post_id", "user_id")
);

CREATE TABLE "sessions" (
  "id" uuid PRIMARY KEY,
  "user_id" int NOT NULL,
  "refresh_token" varchar NOT NULL,
  "user_agent" varchar NOT NULL,
  "client_ip" varchar NOT NULL,
  "is_blocked" boolean NOT NULL DEFAULT false,
  "expires_at" timestamptz NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT (now())
);

ALTER TABLE "posts" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "post_tags" ADD FOREIGN KEY ("post_id") REFERENCES "posts" ("id");

ALTER TABLE "post_tags" ADD FOREIGN KEY ("tag_id") REFERENCES "tags" ("id");

ALTER TABLE "post_categories" ADD FOREIGN KEY ("post_id") REFERENCES "posts" ("id");

ALTER TABLE "post_categories" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("id");

ALTER TABLE "featured_stories" ADD FOREIGN KEY ("post_id") REFERENCES "posts" ("id");

ALTER TABLE "profiles" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "user_posts" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "user_posts" ADD FOREIGN KEY ("post_id") REFERENCES "posts" ("id");

ALTER TABLE "user_followers" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "user_followers" ADD FOREIGN KEY ("follower_id") REFERENCES "users" ("id");

ALTER TABLE "comments" ADD FOREIGN KEY ("post_id") REFERENCES "posts" ("id");

ALTER TABLE "comments" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "post_likes" ADD FOREIGN KEY ("post_id") REFERENCES "posts" ("id");

ALTER TABLE "post_likes" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "sessions" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");
