// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: posts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deletePost = `-- name: DeletePost :exec
DELETE FROM posts 
WHERE id = $1
`

func (q *Queries) DeletePost(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deletePost, id)
	return err
}

const getPost = `-- name: GetPost :one
SELECT id, user_id, title, summary, content, cover_image, created_at, updated_at, likes 
FROM posts 
WHERE id = $1
`

func (q *Queries) GetPost(ctx context.Context, id int32) (Post, error) {
	row := q.db.QueryRow(ctx, getPost, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Summary,
		&i.Content,
		&i.CoverImage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Likes,
	)
	return i, err
}

const getPosts = `-- name: GetPosts :many
SELECT id, user_id, title, summary, content, cover_image, created_at, updated_at, likes 
FROM posts 
ORDER BY id LIMIT $1 OFFSET $2
`

type GetPostsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetPosts(ctx context.Context, arg GetPostsParams) ([]Post, error) {
	rows, err := q.db.Query(ctx, getPosts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Post{}
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Summary,
			&i.Content,
			&i.CoverImage,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Likes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertPost = `-- name: InsertPost :one
INSERT INTO posts (user_id, title, summary, content, cover_image, created_at, updated_at, likes) 
VALUES ($1, $2, $3, $4, $5, $6, $7, $8) 
RETURNING id, user_id, title, summary, content, cover_image, created_at, updated_at, likes
`

type InsertPostParams struct {
	UserID     pgtype.Int4        `json:"user_id"`
	Title      string             `json:"title"`
	Summary    string             `json:"summary"`
	Content    string             `json:"content"`
	CoverImage pgtype.Text        `json:"cover_image"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	Likes      pgtype.Int4        `json:"likes"`
}

func (q *Queries) InsertPost(ctx context.Context, arg InsertPostParams) (Post, error) {
	row := q.db.QueryRow(ctx, insertPost,
		arg.UserID,
		arg.Title,
		arg.Summary,
		arg.Content,
		arg.CoverImage,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Likes,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Summary,
		&i.Content,
		&i.CoverImage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Likes,
	)
	return i, err
}

const updatePost = `-- name: UpdatePost :one
UPDATE posts 
    SET
    title = COALESCE($1,title), 
    summary = COALESCE($2,summary), 
    content = COALESCE($3,content), 
    cover_image = COALESCE($4,cover_image),  
    likes = COALESCE($5,likes)
    WHERE id = $6
RETURNING id, user_id, title, summary, content, cover_image, created_at, updated_at, likes
`

type UpdatePostParams struct {
	Title      pgtype.Text `json:"title"`
	Summary    pgtype.Text `json:"summary"`
	Content    pgtype.Text `json:"content"`
	CoverImage pgtype.Text `json:"cover_image"`
	Likes      pgtype.Int4 `json:"likes"`
	ID         int32       `json:"id"`
}

func (q *Queries) UpdatePost(ctx context.Context, arg UpdatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, updatePost,
		arg.Title,
		arg.Summary,
		arg.Content,
		arg.CoverImage,
		arg.Likes,
		arg.ID,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Summary,
		&i.Content,
		&i.CoverImage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Likes,
	)
	return i, err
}
