package localization

// DO NOT EDIT: This file is automatically generated by the musale CLI tool.

const (
	Errors_CanNotConnectToDb = "Errors.CanNotConnectToDb"
	Errors_ErrorFromWaitGroup = "Errors.ErrorFromWaitGroup"
	Errors_HttpGateway = "Errors.HttpGateway"
	Errors_HttpGatewayShutdown = "Errors.HttpGatewayShutdown"
	Errors_InternalError = "Errors.InternalError"
	Errors_MigrateUp = "Errors.MigrateUp"
	Errors_MigrationInstance = "Errors.MigrationInstance"
	Info_GracefulShutdown = "Info.GracefulShutdown"
	Info_StartHttp = "Info.StartHttp"
	Info_StopHttp = "Info.StopHttp"
	Pagination_pageError = "Pagination.pageError"
	Pagination_sizeError = "Pagination.sizeError"
	Success_Migrate = "Success.Migrate"
	User_RegisterSuccess = "User.RegisterSuccess"
)
